package ca.mcgill.ecse.cheecsemanager.fxml.controller.purchase;

import static ca.mcgill.ecse.cheecsemanager.application.CheECSEManagerApplication.PACKAGE_ID;

import ca.mcgill.ecse.cheecsemanager.fxml.controller.farmer.FarmerSelectionOneController;
import ca.mcgill.ecse.cheecsemanager.fxml.layout.ToastFactory;
import ca.mcgill.ecse.cheecsemanager.fxml.state.NavigationState;
import ca.mcgill.ecse.cheecsemanager.fxml.state.PageType;
import ca.mcgill.ecse.cheecsemanager.fxml.state.TOForm;
import ca.mcgill.ecse.cheecsemanager.fxml.util.FormHelper;
import ca.mcgill.ecse.cheecsemanager.fxml.util.InvalidInputException;
import ca.mcgill.ecse.cheecsemanager.fxml.util.PageSwitchEvent;
import ca.mcgill.ecse.cheecsemanager.model.CheeseWheel.MaturationPeriod;
import java.io.IOException;
import java.net.URL;
import java.sql.Date;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class PurchaseFormController implements Initializable {
  @FXML private Label labelId;
  @FXML private TextField inputFieldId;
  @FXML private Label labelTransactionDate;
  @FXML private DatePicker inputFieldTransactionDate;
  @FXML private Label labelNrCheeseWheels;
  @FXML private TextField inputFieldNrCheeseWheels;
  @FXML private Label labelMonthsAged;
  @FXML private ChoiceBox<MaturationPeriod> choiceBoxMonthsAged;
  @FXML private Label labelFarmer;
  @FXML private Button buttonSelectFarmer;
  private String farmer;

  @FXML private Button buttonCancel;
  @FXML private Button buttonSave;

  @FXML private Text textError;

  @Override
  public void initialize(URL url, ResourceBundle resourceBundle) {
    // Initialize Label text with formatting
    labelId.setText(FormHelper.convertCamelCaseToWords("id"));
    // Disable Autounique keys as they are autogenerated
    inputFieldId.setDisable(true);
    inputFieldId.setText("Autogenerated");
    // Initialize Label text with formatting
    labelTransactionDate.setText(FormHelper.convertCamelCaseToWords("transactionDate"));
    // Initialize Label text with formatting
    labelNrCheeseWheels.setText(FormHelper.convertCamelCaseToWords("nrCheeseWheels"));
    // Initialize Label text with formatting
    labelMonthsAged.setText(FormHelper.convertCamelCaseToWords("monthsAged"));
    // Initialize enum dropdown
    choiceBoxMonthsAged.getItems().addAll(MaturationPeriod.values());
    // Initialize Label text with formatting
    labelFarmer.setText(FormHelper.convertCamelCaseToWords("farmer"));
  }

  @FXML
  private void onSave(ActionEvent event) {
    try {
      // Assign Default value for Autounique key as its not in use
      int id = Integer.MAX_VALUE;
      Date transactionDate = Date.valueOf(inputFieldTransactionDate.getValue());
      int nrCheeseWheels = Integer.parseInt(inputFieldNrCheeseWheels.getText());
      MaturationPeriod monthsAged = choiceBoxMonthsAged.getValue();
      String savedStatus = "";
      // Perform Add Operation

      // Validate Controller response
      if (!savedStatus.isEmpty())
        throw new InvalidInputException(savedStatus);
      else {
        textError.setText("");
        buttonSave.setDisable(true);
        ToastFactory.createSuccess(
            buttonSave, "Successfully saved item. Redirecting back to table...");
        FormHelper.triggerAfterDelay(()
                                         -> buttonCancel.fireEvent(new PageSwitchEvent(
                                             new NavigationState<>(null, PageType.BACK, null))),
            2);
      }

    } catch (RuntimeException e) {
      textError.setText(FormHelper.formatTextMessage(e));
    }
  }

  public void onCancel(ActionEvent actionEvent) {
    buttonCancel.fireEvent(new PageSwitchEvent(new NavigationState<>(null, PageType.BACK, null)));
  }

  @FXML
  public void onSelectFarmer(ActionEvent actionEvent) {
    System.out.println("Select Farmer");
    try {
      FXMLLoader fxmlLoader = new FXMLLoader(
          getClass().getResource(PACKAGE_ID + "view/page/farmer/FarmerSelectionOne.fxml"));
      Parent tempContainer = fxmlLoader.load();
      // Get controller
      FarmerSelectionOneController controller = fxmlLoader.getController();
      controller.setAction(this::onFarmerSelected, farmer, null);
      Stage stage = new Stage();
      stage.setTitle("Select Farmer");
      stage.initModality(Modality.APPLICATION_MODAL);
      Scene scene = new Scene(tempContainer, 640, 480);
      scene.getStylesheets().add(
          getClass().getResource(PACKAGE_ID.concat("style/main.css")).toExternalForm());
      stage.setScene(scene);
      stage.showAndWait();

    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  public void onFarmerSelected(String farmer) {
    this.farmer = farmer;
    this.buttonSelectFarmer.setText(farmer);
  }
}
